#!/usr/bin/python

from plan10admin import Plan10

def main():
    app = Plan10()
    for vm in app.domains:
        if vm.klass == 'DispVM' and not vm.is_running():
            if vm.auto_cleanup:
                del app.domains[vm.name]

main()
